### ISSUE TITLE
RSS Update Feed

### ISSUE THREAD

**Issue by Jonthetrombonist** [ArkansasRepeaterCouncil/website#617]
**Is your feature request related to a problem? Please describe.**
         No

**Describe the solution you'd like**
        A RSS feed (Or maybe email notifications?) of the "Recent updates" section on the site. This is to alert repeater owners of new updates and could serve as a way to push notifications or special announcements (Maybe the annual meeting reminder?) to the members as well. Perhaps the RSS feed could be pushed on a user selected basis (Daily, Weekly, Monthly, Yearly) much like groups.io, if you are familiar with that.

**Describe alternatives you've considered**

**Additional information**
  I'll quit spamming the Issue inbox now lol!

**Comment by JoshuaCarroll** [comment]
Ok, sorry... I opened this ticket and got lost down the rabbit hole that is groups.io.  Thanks for that!  LOL

Well actually.. This already exists.  I created it so that our team could see the updates in Slack.  

You can access it at this URL: https://repeatercoordinationservice.azurewebsites.net/api/ListRecentChanges

I suppose I should add an RSS link to the home page next to the most recent changes list.

**Comment by Jonthetrombonist** [comment]
Thanks Josh! It's added to my RSS Feed list.

Have you not seen Groups.io before? I like to think it's like a email
reflector for the 21st century LOL

A RSS feed is a bit of a programmer/nerd thing but I can see some others
get on the band wagon. I use mine for groups.io lists, Weather alerts from
Noaa, etc.

**Comment by JoshuaCarroll** [comment]
This has been addressed and accepted so I'll close this ticket now.  Thanks for all of your input and support.
